# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
  :verbose: false
  :concurrency: 25
  :require: './lib/workers/_worker.rb'
  :queues:
    - checker