# frozen_string_literal: true

source 'http://rubygems.org' do
  gem 'awrence'
  gem 'dry-validation'
  gem 'falcon'
  gem 'faraday'
  gem 'interactor', '~> 3.0'
  gem 'mongoid'
  gem 'puma', '~> 4.0'
  gem 'roda', '~> 3.38'

  group :development do
    gem 'pry-nav'
    gem 'rack-test'
    gem 'rspec'
    gem 'rubocop-performance'
    gem 'rubocop-rspec'
    gem 'webmock'
  end

  group :test do
    gem 'database_cleaner-mongoid'
    gem 'factory_bot'
    gem 'mongoid-rspec'
    gem 'vcr'
  end
end
