# frozen_string_literal: true

source 'http://rubygems.org' do
  gem 'falcon'
  gem 'puma', '~> 4.0'
  gem 'roda', '~> 3.38'
  gem 'mongoid'
  gem 'dry-validation'
  gem "interactor", "~> 3.0"
  gem "awrence"
  gem "faraday"

  group :development do
    gem 'pry-nav'
    gem 'rack-test'
    gem 'rspec'
    gem 'rubocop-performance'
    gem 'rubocop-rspec'
    gem 'webmock'
  end

  group :test do
    gem 'vcr'
    gem 'factory_bot'
    gem 'mongoid-rspec'
    gem 'database_cleaner-mongoid'
  end
end
